export const examinerData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    speciality: "Mathematics",
    location: "New York",
    password: "password123",
    confirmPassword: "password123",
    cohort: "cohort 1",
    track: "frontend",
    stations: ["station1", "station3"],
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    speciality: "Physics",
    location: "Los Angeles",
    password: "password456",
    confirmPassword: "password456",
    cohort: "cohort 2",
    track: "frontend",
    stations: ["station2"],
  },
  {
    id: 3,
    firstName: "Sam",
    lastName: "Wilson",
    email: "sam.wilson@example.com",
    speciality: "Chemistry",
    location: "Chicago",
    password: "password789",
    confirmPassword: "password789",
    cohort: "cohort 3",
    track: "backend",
    stations: ["station1", "station2"],
  },
  {
    id: 4,
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    speciality: "Biology",
    location: "Houston",
    password: "password101",
    confirmPassword: "password101",
    cohort: "cohort 1",
    track: "backend",
    stations: ["station3"],
  },
  {
    id: 5,
    firstName: "Bob",
    lastName: "Martinez",
    email: "bob.martinez@example.com",
    speciality: "Computer Science",
    location: "San Francisco",
    password: "password102",
    confirmPassword: "password102",
    cohort: "cohort 2",
    track: "frontend",
    stations: ["station2", "station3"],
  },
];

export const stationData = [
  {
    id: 1,
    stationName: "Main Exam Hall",
    location: "Building A, Room 101",
    assignedExaminers: 3,
    track: "frontend",
    stations: ["station1"],
  },
  {
    id: 2,
    stationName: "Science Lab",
    location: "Building B, Room 203",
    assignedExaminers: 2,
    track: "backend",
    stations: ["station2", "station4"],
  },
  {
    id: 3,
    stationName: "Computer Lab",
    location: "Building C, Room 305",
    assignedExaminers: 1,
    track: "backend",
    stations: ["station3", "station5"],
  },
  {
    id: 4,
    stationName: "Physics Lab",
    location: "Building D, Room 204",
    assignedExaminers: 4,
    track: "Frontend",
    stations: ["station1", "station4"],
  },
  {
    id: 5,
    stationName: "Chemistry Lab",
    location: "Building E, Room 302",
    assignedExaminers: 3,
    track: "backend",
    stations: ["station1", "station4"],
  },
];
